config/routes.rb
SeenChild::Application.routes.draw do

   controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :children
  resources :children
  resources :pages
  resources :users

  match '/home',:to => 'pages#home'
  match '/contact', :to => 'pages#contact', :as => :contact
  match '/about',   :to => 'pages#about', :as => :about
  match '/report_a_child', :to => 'pages#report_a_child', :as => :report
  match '/children(.:format)', :to => 'children#index'
  match '/admin(.:format)', :to => 'admin#index', :as => :admin
  match '/user(.:format)', :to => 'users#index',:as => :user

  root  :to => "pages#home"

end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :user
  validates :name, :police_abstract_no, :gender, :missing_city, :presence => true
  validates :police_abstract_no, :uniqueness => true

end

app/models/child_status.rb
class Child_status < ActiveRecord::Base
  STATUS = ["Search in Progress","Reunited with Family","Compromised"]
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :children
    before_destroy :ensure_not_referenced_by_any_child

    validates :email, :presence  => true, :uniqueness => true
    validates :password, :confirmation => true
    attr_accessor :password_confirmation
    attr_reader :password

    validate :password_must_be_present

    def User.authenticate(email,password)
        if user = find_by_email(email)
          if user.hashed_password == encrypt_password(password,user.salt)
            user
          end
        end
      end

    def User.encrypt_password(password, salt)
       Digest::SHA2.hexdigest(password + "wibble" + salt)
    end

    #to substitute the attr_accessor, which behind the scenes calls a reader and writer eg password=
    #since the method ends in an equals sign means that it can be assigned to. We want to implement
    #our own public method to have the writer to also create a new salt and set the hashed password

    def password=(password)
      @password = password
      if password.present?
        generate_salt
        self.hashed_password = self.class.encrypt_password(password,salt)
      end
    end

    private
      def ensure_not_referenced_by_any_child
         if children.empty?
           return true
         else
           errors.add(:base, 'This user is referenced by some children.')
           return false
         end
      end

      def password_must_be_present
        errors.add(:password, "Blank password")unless hashed_password.present?
      end

      def generate_salt
        self.salt = self.object_id.to_s + rand.to_s
      end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
  protect_from_forgery

  layout :layout_by_resource

  protected
    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, :notice => "Please log in"
      end
    end

    def layout_by_resource
      if @child_crud
        "layout_for_crud"
      else
        "application"
      end
    end
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  #skip_before_filter :authorize

  # GET /children
  # GET /children.json
  def index
    @children = Child.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @children }
    end
  end

  # GET /children/1
  # GET /children/1.json
  def show
    @child = Child.find(params[:id])
    #used to determine layout used
    @child_crud = true

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @child }
    end
  end

  # GET /children/new
  # GET /children/new.json
  def new
    @child = Child.new
    @child_crud = true

    respond_to do |format|
      format.html # new.html.erb
      format.html {render}
      format.json { render json: @child }
    end
  end

  # GET /children/1/edit
  def edit
    @child = Child.find(params[:id])
    @child_crud = true
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(params[:child])
    @child_crud = true

    respond_to do |format|
      if @child.save
        format.html { redirect_to children_url, notice: 'Child was successfully created.' }
        format.js   { @current_child = @child}
        format.json { render json: @child, status: :created, location: @child }
      else
        format.html { render :layout => false, action: "new"}
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /children/1
  # PUT /children/1.json
  def update
    @child = Child.find(params[:id])

    respond_to do |format|
      if @child.update_attributes(params[:child])
        format.html { redirect_to children_url, notice: 'Child was successfully updated.' }
        format.js   { @current_child = @child}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child = Child.find(params[:id])
    @child.destroy

    respond_to do |format|
      format.html { redirect_to children_url }
      format.json { head :ok }
    end
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authorize
  def home
  end

  def about
  end

  def report_a_child
  end

  def contact
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize

  def new

  end

  def create
     if user = User.authenticate(params[:email],params[:password])
      session[:user_id] = user.id
      if user.email = "admin@seenchild.org"
        redirect_to users_path
      else
        redirect_to report_path
      end
    else
      redirect_to login_url, :alert => "Invalid username or password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice =>"Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, :only => [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/children/_form.html.erb
<div id="main_child_form">
    <%= form_for(@child) do |f| %>
      <% if @child.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

          <ul>
          <% @child.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <table>
           <tr>
                <td><%= f.label :name %></td>
                <td><%= f.text_field :name %></td>
           </tr>
           <tr>
                <td><%= f.label :date_of_birth %></td>
                <td><%= f.date_select :date_of_birth %></td>
           </tr>
           <tr>
                <td><%= f.label :status %></td>
                <td><%= f.select :status, Child_status::STATUS,
                                     :prompt => 'Search in progress',
                                     :disabled => true %></td>
            </tr>
            <tr>
                <td><%= f.label :police_abstract_no %></td>
                <td><%= f.text_field :police_abstract_no%></td>
            </tr>
            <tr>
                <td><%= f.label :gender %></td>
                <td><%= f.text_field :gender %></td>
            </tr>
            <tr>
                <td><%= f.label :missing_town %></td>
                <td><%= f.text_field :missing_town %></td>
            </tr>
            <tr>
                <td><%= f.label :missing_city %></td>
                <td><%= f.text_field :missing_city %></td>
            </tr>
            <tr>
                <td><%= f.label :additional_info %></td>
                <td><%= f.text_area :additional_info, :rows => 3 %></td>
            </tr>
      </table>
      <div class="actions">
         <%= f.submit :remote => true%>
      </div>
    <% end %>
</div>

app/views/children/edit.html.erb
<h1>Edit Child Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @child, :onclick =>
            "Modalbox.show(this.href, {title: this.title, width: 600}); return false;"%> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<div id= "child_list">
    <h1>Listing children</h1>
    <table>
     <% @children.each do |child| %>
     <% if child == @current_child %>
        <tr id= "current_child">
     <% else %>
      <tr class="<% cycle('list_line_odd','list_line_even')%>">
        <!--show image here-->
         <td class="list_description">
           <dl>
              <dt><%= child.name %>: <%= child.missing_city %> </dt>
              <dd><%= truncate(strip_tags(child.additional_info),
                       :length => 120)%></dd>
           </dl>
         </td>
         <td class="list_actions">
            <%= link_to 'Show', child, :onclick =>
            "Modalbox.show(this.href, {title: this.title, width: 600}); return false;" %><br/>
            <%= link_to 'Edit', edit_child_path(child), :onclick =>
            "Modalbox.show(this.href, {title: this.title, width: 600}); return false;"%><br/>
         </td>
        </tr>
     <% end %>
     <% end %>
    </table>
</div>
<br />

<%= link_to 'Add Child Information', new_child_path, :onclick =>
            "Modalbox.show(this.href, {title: this.title, width: 600}); return false;"%>

app/views/children/new.html.erb
<h1>Enter Child Information</h1>

<%= render 'form' %>

<%= link_to 'Back', children_path %>

app/views/children/show.html.erb
<h1><%= @child.name %></h1>
<p id="notice"><%= notice %></p>
<table>
           <tr>
                <td>Name:</td>
                <td><%= @child.name %></td>
           </tr>
           <tr>
                <td>Date of birth:</td>
                <td><%= @child.date_of_birth %></td>
           </tr>
           <tr>
                <td>Status:</td>
                <td><%= @child.status %></td>
            </tr>
            <tr>
                <td>Police abstract no:</td>
                <td><%= @child.police_abstract_no%></td>
            </tr>
            <tr>
                <td>Created by:</td>
                <td><%= @child.created_by %></td>
            </tr>

            <tr>
                <td>Gender:</td>
                <td><%= @child.gender %></td>
            </tr>
            <tr>
                <td>Missing town:</td>
                <td><%= @child.missing_town %></td>
            </tr>
            <tr>
                <td>Missing city:</td>
                <td><%= @child.missing_city %></td>
            </tr>
            <tr>
                <td>Additional info:</td>
                <td><%= @child.additional_info %></td>
            </tr>
      </table>
 <br />
<%= link_to 'Edit', edit_child_path(@child),:onclick =>
            "Modalbox.show(this.href, {title: this.title, width: 600}); return false;" %> |
<%= link_to 'Back', children_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seen Child: Help Find These Children</title>
  <%= stylesheet_link_tag    "scaffolds"%>
  <%= stylesheet_link_tag    "modalbox", :media=> "screen"%>
  <%= stylesheet_link_tag    "children" , :media => "all" %>
  <%= javascript_include_tag "prototype" %>
  <%= javascript_include_tag "scriptaculous" %>
  <%= javascript_include_tag "modalbox" %>
  <%= csrf_meta_tags %>
</head>
<body id= "child">
    <div id="banner">
      <%= @page_title || "Seen Child: Rescue The Children" %>
    </div>
   <div id="columns">
    <div id="side">
      <div id="links">
          <%= link_to "Home", root_path %> <br />
          <%= link_to "Report_a_Child", report_path %> <br />
          <%= link_to "Missing Children", children_path %> <br />
          <%= link_to 'About', about_path %> <br />
          <%= link_to 'Contact', contact_path %> <br />
      </div>
      <% if session[:user_id] %>
          <br />
          <div id="links">

              <%= link_to "View Users", users_url %> <br />
              <%= button_to 'Logout', logout_path, :method => :delete %> <br />
          </div>
      <%end%>
    </div>
  </div>
  <div id="main">
     <%= yield %>
  </div>
</body>
</html>

app/views/layouts/layout_for_crud.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seen Child: Help Find These Children</title>
  <%= stylesheet_link_tag    "scaffolds"%>
  <%= stylesheet_link_tag    "modalbox", :media=> "screen"%>
  <%= stylesheet_link_tag    "children" , :media => "all" %>
  <%= javascript_include_tag "prototype" %>
  <%= javascript_include_tag "scriptaculous" %>
  <%= javascript_include_tag "modalbox" %>
  <%= csrf_meta_tags %>
</head>
<body id= "child">
  <div>
     <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div id ="about">
<h1>Introduction</h1>
<h3>Our Vision</h3>
   <ul>
     <li>To assist create national awareness and proactive communities in relation to missing children
         and child trafficking.</li>
     <li>To have in place an effective network that can be activated to find missing children.</li>
    </ul>
  <h3>Our Mission</h3>
   <ul>
     <li>To work with the police and IT systems to ensure that children at risk do not become victims</li>
    </ul>
  <h3>Our Objectives</h3>
   <ul>
     <li>To ensure that relevant systems are in place to find the child and follow up as frequently as possible</li>
    </ul>
</div>

app/views/pages/contact.html.erb
<div id= "contact">
<h1>Contact Us</h1>
    <table>
      <tr>
        <td>Address: </td>
        <td>George Building</td>
      </tr>
      <tr>
        <td></td>
        <td>Off Main Rd, Pittsburgh</td>
      </tr>
      <tr>
        <td></td>
        <td>USA.</td>
      </tr>
      <tr>
        <td>E-mail:</td>
        <td>email@seenchild.org</td>
      </tr>
      <tr>
        <td>Office:</td>
        <td>1-123-123-1234</td>
      </tr>
      <tr>
        <td>Emergency Tel:</td>
        <td>800-SEEN-CHILD</td>
      </tr>
    </table>
</div>

app/views/pages/home.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>
<h1>Seen Child: Not For Sale</h1>
<body>
<table>
  <tr>
    <td>
      <p style="text-align: left;">
       According to a International Organization for Migration, there are about 800 000
       people trafficked across international borders annually. This figure does not include
       those trafficked within our countries.</p>
       <p style="text-align: left;">Cheap labour, sexual exploitation and certain criminal activities are the cause of child
       trafficking. </p>
      <a href ="http://www.iom.int/jahia/page748.html">More Information</a>
    </td>
    <td><%= image_tag("child_image.jpg", :alt => "child-trafficking.jpg- theheatmag.com",
                      :title =>"child-trafficking.jpg- theheatmag.com") %></td>
  </tr>
</table>

</body>

app/views/pages/report_a_child.html.erb
<div id="report_child">
    <h1>Report Missing Child</h1>
    <p>After completion of a police abstract form (found at the police station):</p>
    <ol>
      <li>
          Visit our offices, <%= link_to 'see location', contact_path, :onclick =>
            "Modalbox.show(this.href, {title: this.title, width: 600}); return false;"%> or,
      </li>
      <li>
         Email/Fax the information of the child, details of the situation, the police case number
         as well as a photo of the child to: <a href="mailto:email@seenchild.co.ke">email@seenchild.org</a>
      </li>
    </ol>
</div>
<br />
<%= link_to 'Add Child Information', 'children/new', :onclick =>
            "Modalbox.show(this.href, {title: this.title, width: 600}); return false;"%>

app/views/users/_form.html.erb
<div class = "users_form">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
     <fieldset>
     <legend> Enter User Detail</legend>
          <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name, :size => 40%>
          </div>
          <div class="field">
            <%= f.label :email %><br />
            <%= f.text_field :email, :size => 40 %>
          </div>
          <div class="field">
            <%= f.label :phone_no %><br />
            <%= f.text_field :phone_no, :size => 40 %>
          </div>
          <div class="field">
            <%= f.label :password, 'Password' %><br />
            <%= f.password_field :password, :size => 40 %>
          </div>
          <div class="field">
            <%= f.label :password_confirmation, 'Confirm Password' %><br />
            <%= f.password_field :password_confirmation, :size => 40 %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
     </fieldset>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
 <% if notice %>
    <p id= "notice"><%= notice %></p>
 <%end%>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone no</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.phone_no %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Phone no:</b>
  <%= @user.phone_no %>
</p>

<%= link_to 'Edit', edit_user_path(@user)%> |
<%= link_to 'Back', users_path %>